version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sales_db
    volumes:
      - db_1:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db_1: 
    driver: local